### ISSUE TITLE
Feature Request, Sort columns

### ISSUE THREAD

**Issue by bseishen** [svpernova09/midsouthmakers-rfid#10]
Have the ability to sort columns on the members view/logs/etc

**Comment by svpernova09** [comment]
I've got the first bit of this complete, which was to overhaul & bring all the HTML & CSS up to date (it was all really old versions of stuff)

**Comment by svpernova09** [comment]
New UI is live on the site. Let me know if anything looks weird/broken. Now I can start looking into actually implementing column sorting.

**Comment by svpernova09** [comment]
Tables have now been turned into data tables (And allows searching!)
