### ISSUE TITLE
Feature Request, Logging

### ISSUE THREAD

**Issue by bseishen** [svpernova09/midsouthmakers-rfid#12]
Have Logs update Last Login time in the database. Use new logging on the log-viewer page.

**Comment by svpernova09** [comment]
I was incorrect in telling you that the log viewer wasn't reading the login attempts. It is indeed reading from the login attempts, and I've updated the page to not worry about the file's last modified date.

> Have Logs update Last Login time in the database.

Not sure what you mean here, I just tested that the login attempt endpoint is updating the members' last_login field.

**Comment by bseishen** [comment]
rsync logs are going away on v2 hardware I'm assuming and just using API endpoints.

**Comment by svpernova09** [comment]
> rsync logs are going away on v2 hardware I'm assuming and just using API endpoints.

We're all set then.
