### ISSUE TITLE
+/- Symbols

### ISSUE THREAD

**Issue by bseishen** [svpernova09/midsouthmakers-rfid#6]
Just personal opinion, but the +/- symbols are difficult to read on "Active" column in the member database. They are also used in Results column in the log viewer.

**Comment by svpernova09** [comment]
new repo who dis?

**Comment by bseishen** [comment]
Lol

**Comment by svpernova09** [comment]
The table cell backgrounds should be showing green + and red - colors. Do the icons need to be bigger? Different icons?

**Comment by svpernova09** [comment]
Added the red/green to the log viewer. Let me know if you want more changes.
